services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MichielRoos\H5p\Domain\Repository\ContentRepository:
    arguments:
      $objectManager: '@TYPO3\CMS\Extbase\Object\ObjectManager'

  MichielRoos\H5p\Middleware\H5pRouteResolver:
    arguments:
      $requestFactory: '@TYPO3\CMS\Core\Http\RequestFactory'
      $linkService: '@TYPO3\CMS\Core\LinkHandling\LinkService'
